<?php
    $title = 'Delete New Post';
    $this->headTitle($title);
?>

<div class="jumbotron">
    <h1>Delete <span class="zf-green">Post</span></h1>
</div>

<?php
    $url = $this->url('post', ['action' => 'delete', 'id' => $id]);
?>

<form action="<?= $url; ?>" method="post">
    <p>Post: <?= $post->title; ?></p>
    <p>Are you sure?</p>
    <input type="hidden" name="id" value="<?= $id; ?>">
    <input type="submit" name="delete" value="Yes" class="btn btn-danger">
    <a href="<?= $this->url('post', ['action' => 'index']) ?>" class="btn btn-default">No</a>
</form>
