<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Posts</span></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<a href="<?php echo $this->url('post', ['action' => 'add']) ?>" class="btn btn-primary">Add Post</a>

<table class="table table-striped table-hover table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Category</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <?php if(count($posts) > 0) { ?>
        <?php foreach($posts as $post) { ?>
            <tr>
                <td><?php echo $post->id; ?></td>
                <td><?php echo $post->title; ?></td>
                <td><?php echo $post->description; ?></td>
                <td><?php echo $post->category; ?></td>
                <td>
                    <a href="<?php echo $this->url('post', ['action' => 'view', 'id' => $post->id]) ?>" class="label label-primary">View</a>
                     <a href="<?php echo $this->url('post', ['action' => 'edit', 'id' => $post->id]) ?>" class="label label-success">Edit</a>
                     <a href="<?php echo $this->url('post', ['action' => 'delete', 'id' => $post->id]) ?>" class="label label-danger">Delete</a>
                 </td>
            </tr>
        <?php } ?>
    <?php } else { ?>
        <tr>
            <td colspan="5">No Results</td>
        </tr>
    <?php } ?>

    </tbody>
</table>